import { describe, it, expect } from 'vitest'
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { PRODUCTS } from '../api/fixtures/products'
import { CATEGORIES } from '../api/fixtures/categories'

/**
 * The loud half of the product-image pipeline.
 *
 * `productImages.ts` maps `src/assets/products/<slug>.<ext>` onto products by
 * filename. A filename is a string, and a mistyped one resolves to nothing at
 * all — the tile falls back and no one notices. So the directory is checked
 * against the catalogue here rather than trusted:
 *
 * - a file whose slug matches no product fails the suite outright;
 * - everything still missing is written to `REQUIRED.md`, which is committed,
 *   so the list of photographs to source is a file someone can work through
 *   rather than a thing to be rediscovered.
 */

const DIR = join(__dirname, '..', 'assets', 'products')
const MANIFEST = join(DIR, 'REQUIRED.md')
const IMAGE_EXT = /\.(jpe?g|png|webp|avif)$/i

const slugOf = (productId: string) => productId.replace(/^prod_/, '')

const present = new Set(
  readdirSync(DIR)
    .filter((f) => IMAGE_EXT.test(f))
    .map((f) => f.replace(IMAGE_EXT, '')),
)

const CATEGORY_NAME = new Map(CATEGORIES.map((c) => [c.slug, c.name]))

function renderManifest(): string {
  const missing = PRODUCTS.filter((p) => !present.has(slugOf(p.id)))
  const byCategory = new Map<string, typeof missing>()
  for (const p of missing) {
    const key = p.categorySlug ?? 'uncategorised'
    const list = byCategory.get(key)
    if (list) list.push(p)
    else byCategory.set(key, [p])
  }

  const lines: string[] = [
    '# Product photographs still needed',
    '',
    'Generated by `product-images.test.ts` — do not edit by hand; rerun the',
    'suite after adding files and commit the result.',
    '',
    `${missing.length} of ${PRODUCTS.length} products have no photograph of their own.`,
    'Each one falls back to category photography, which is a picture of the',
    'aisle rather than of the product.',
    '',
    'Drop each file into this directory under the filename shown.',
    '',
  ]
  for (const [slug, items] of [...byCategory.entries()].sort()) {
    lines.push(`## ${CATEGORY_NAME.get(slug) ?? slug} (\`${slug}\`)`, '')
    for (const p of items.sort((a, b) => a.name.localeCompare(b.name))) {
      lines.push(`- [ ] \`${slugOf(p.id)}.jpg\` — ${p.name}${p.brand ? ` (${p.brand})` : ''}`)
    }
    lines.push('')
  }
  return lines.join('\n')
}

describe('product photography', () => {
  it('has no file that matches no product', () => {
    const known = new Set(PRODUCTS.map((p) => slugOf(p.id)))
    const orphans = [...present].filter((slug) => !known.has(slug))
    // A file here is dead weight: nothing renders it, and the product it was
    // meant for still shows a category photo.
    expect(orphans).toEqual([])
  })

  it('keeps REQUIRED.md in step with the catalogue', () => {
    const expected = renderManifest()
    const actual = existsSync(MANIFEST) ? readFileSync(MANIFEST, 'utf8') : ''
    if (actual !== expected) {
      writeFileSync(MANIFEST, expected, 'utf8')
      throw new Error(
        'REQUIRED.md was out of date and has been rewritten — commit the change.',
      )
    }
    expect(actual).toBe(expected)
  })
})
